version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        # image: php:7.4-fpm
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'chinhnv'
            MYSQL_PASSWORD: '123456'
            MYSQL_DATABASE: 'docker-demo'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 33062:3306
    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8001:80
      environment:
        - PMA_ARBITRARY=1
volumes:
    mysqldata: {}